twig:
    default_path: '%kernel.project_dir%/templates'

    # Configures the Symfony application to use Bootstrap 5 styles when rendering forms
    form_themes: ['bootstrap_5_layout.html.twig']


when@test:
    twig:
        strict_variables: true
